kind: Deployment
apiVersion: apps/v1
metadata:
  name: barista
spec:
  selector:
    matchLabels:
      app: barista
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
        version: v1
    spec:
      containers:
      - name: barista
        image: de.icr.io/cee-<your-name>-workshop/barista:1
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://barista:9080/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://barista:9080/health | grep -q barista"]
          initialDelaySeconds: 40